name: Auto Issue Resolver

on:
  schedule:
    # - cron: "0,30 14-20 * * *" # JST 23:00-05:30 (UTC 14:00-20:30)
    - cron: "0 15 * * *" # JST 06:00 (UTC 21:00)
  workflow_dispatch: # 手動実行用

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Find and process highest priority Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const priorities = ['high','middle','low'];
            const processedLabel = 'claude-code-requested';

            for (const priority of priorities) {
              const issues = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: priority,
                state: 'open',
                sort: 'created',
                direction: 'desc',
                per_page: 100
              });
              const issue = issues.data.find(i =>
                !i.labels.some(l => l.name === processedLabel)
              );
              if (issue) {
                await github.rest.issues.createComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  body: [
                    `@claude このIssue #${issue.number} を解決してください。`,
                    '',
                    '**タイトル**: ' + issue.title,
                    '',
                    '**説明**:',
                    issue.body || '説明なし',
                    '',
                    `優先度: ${priority}`
                  ].join('\n')
                });
                await github.rest.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue.number,
                  labels: [processedLabel]
                });
                console.log('Triggered Claude Code Action for Issue #' + issue.number);
                return;
              }
            }
            console.log('No unprocessed issues found');